<a href="https://colab.research.google.com/github/gopeshnxg/deeplearning/blob/main/Deeplearning_backprop_tensorflow_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

from keras.backend import dtype
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))


model.get_weights()

new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32), 
                np.array([0., .0,], dtype=np.float32),
                np.array([[0.1],[0.1]], dtype=np.float32),
                np.array([0.], dtype=np.float32)]

new_weights          

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
model.set_weights(new_weights)

model.get_weights()



[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [20]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

import pandas as pd
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

model.compile(loss='mean_squared_error', optimizer=optimizer)

model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=100, verbose=1, batch_size=1)


Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 1.4554
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.3762
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2937
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 1.2526
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 1.2017
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 1.1984
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1431
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1218
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1039
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0844
Epoch 11/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0815
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0839
Epoch 13/100
4/4 [==============================] - 0s 3ms/st